L: 5
aligned_standard: CoM
atom_type_size: 2
batch_size: 32
conditional: true
d_size: 1
diffusion_process: E3
epsilon_prediction: E3
h_hidden_size: 128
initial_atom_num_prediction: CN
lr: 0.0001
m_hidden_size: 128
m_size: 256
max_grad_norm: 100
mlp_x_input: E3
noise_precision: 1.0e-05
num_diffusion_timestep: 5000
num_epochs: 3000
patience: 500
seed: 2024
spectrum_size: 200
t_size: 1
weight_decay: 0
x_equation: E3
x_hidden_size: 128
x_size: 3
