L: 7
atom_type_size: 2
batch_size: 32
compressed_spectrum_size: 32
compressor_hidden_dim:
- 50
conditional: true
d_size: 1
h_hidden_size:
- 128
lr: 0.0001
m_hidden_size:
- 128
m_size: 128
max_grad_norm: 100
noise_precision: 0.001
noise_schedule_power : 2.0
num_diffusion_timestep: 3000
num_epochs: 3000
onehot_scaling_factor: 1.0
patience: 100
seed: 2024
spectrum_size: 100
t_size: 1
to_compress_spectrum: true
weight_decay: 0
x_hidden_size:
- 128
x_size: 3
